name: 'JS Check'

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: dhanusaputra/some-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get Changed Files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
